### ISSUE TITLE
modelClass.getFullIdColumn is not a function

### ISSUE THREAD

**Issue by oliviertassinari** [Vincit/objection-rest#11]
I'm having the following issue when trying to get a model specific id.

> modelClass.getFullIdColumn is not a function

I can't find any other reference to this property in the documentation of `objection-rest`, `objection-find` nor `objection.js`. So I'm assuming this is something needed in order for the library to know the id column to us. Is this correct?

**Comment by kapouer** [comment]
Which versions are you using ? We just updated objection-find to be compatible with objection 0.8, but not objection-rest.

**Comment by oliviertassinari** [comment]
I'm using the following versions:

| Tech         | Version |
|--------------|---------|
| objection-rest  | 0.4.0        |
| objection-find (not in my package.json)       | 0.4.0        |
| objection      | 0.8.9        |

**Comment by oliviertassinari** [comment]
By the way, we have migrated away from Sequelize. Objection has proven to be better for us :).

**Comment by kapouer** [comment]
The objection version you're using is not compatible with objection-rest 0.4.0.
I will update it today.

And BTW i'm not the original author, so feel free to ping @koskimas for kudos and hourras.

**Comment by kapouer** [comment]
Fixed in version 0.5.0

**Comment by oliviertassinari** [comment]
@kapouer Thanks :) !
