### ISSUE TITLE
objection-find@0.3.0?

### ISSUE THREAD

**Issue by manubb** [Vincit/objection-rest#8]
Is it possible to update to objection-find@0.3.0 in dependencies? If so, can you publish an updated version on npm? Thanks!

**Comment by kapouer** [comment]
Yes, but the failure in https://travis-ci.org/Vincit/objection-rest/jobs/191569902 should be addressed before. Maybe it's the test itself that need to be fixed, but if it's not it's a nasty bug.

**Comment by kapouer** [comment]
I reproduce the failure locally. Can you have a look at it ?

**Comment by manubb** [comment]
Ok. This seems unrelated to objection-find version:

- Both tests "PUT /persons/:id/pets" and "PUT /persons/:id/movies" fail and succeed randomly depending on effective insertion order of the two new related items

- This also occurs with objection-find@0.2.0

I will propose a fix for the tests.

**Comment by manubb** [comment]
Can you review, please?

**Comment by kapouer** [comment]
Published version 0.3.0.
